### ISSUE TITLE
Place binary in `$PATH`

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/dep-cnb#10]
Currently the generated binary is placed in `/layers/org.cloudfoundry.dep/app-binary/` folder, which is not picked up by `$PATH`.

Instead, could the binary be placed in `$PATH`, e.g. a folder ending in `/bin`?

**Comment by thitch97** [comment]
Resolved in https://github.com/cloudfoundry/dep-cnb/commit/317952e341327f5c12a9f9d629c6bb4b6576cc95
