### ISSUE TITLE
The `buildpack.yml` requirements of this buildpack are not documented

### ISSUE THREAD

**Issue by cmccarthy101** [cloudfoundry/dep-cnb#2]
What version of the buildpack you are using?
0.0.1

If you were attempting to accomplish a task, what was it you were attempting to do?
Use the buildpack to build a go lang dep application

What did you expect to happen?
I expected the buildpack to work without a buildpack.yml as there is no documentation

What was the actual behavior?

The detect steps fails with no useful error message 

```
[detector] ======== Results ========
[detector] fail: Dep Buildpack
```

I had to read the source code to understand that a buildpack.yml is required. And that the structure of the buildpack.yml should be the following

```
---
import-path: github.com/pivotal/go-hello-world
```

Also have questions about the value of `import-path`. The structure doesn’t seem to be validated and will take any value which just ends up being the application name. Perhaps it might be better named. e.g `application-name`

Can you provide a sample app?
N/A

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ndon55555** [comment]
Hi @cmccarthy101. The `import-path` is not just the name of the app, it’s the fully-qualified import path, so relative import references can be resolved. 

Feel free to reopen if you have any further questions!

**Comment by sclevine** [comment]
For a bit more context: if you aren't using go modules, the buildpack doesn't have enough information to construct a GOPATH that includes your package. For example, if you're pushing an app with the local path of `$GOPATH/src/github.com/pivotal/go-hello-world` from inside the `go-hello-world` directory, the buildpack can't figure out the `github.com/pivotal/go-hello-world` path elements to make sub-package import paths work.

Also worth noting, the `import-path` key must be nested under `go` -- it can't be at the top-level of buildpack.yml.

We do plan to publish a schema for buildpack.yml when we publish CF CNB docs. 😄
