### ISSUE TITLE
Detect failures should show meaningful error messages. 

### ISSUE THREAD

**Issue by cmccarthy101** [cloudfoundry/dep-cnb#3]
What version of the buildpack you are using?
0.0.1

If you were attempting to accomplish a task, what was it you were attempting to do?
Build using the dep-cnb

What did you expect to happen?
When I have a detect failure I get useful error messages

What was the actual behavior?
I just see that the detection fails. 

The following failures return an error of nil. They should return useful error messages to the user about the detection failure. 

https://github.com/cloudfoundry/dep-cnb/blob/c5873ee8857227353198c0080b5fd07ca4f2f0bf/cmd/detect/main.go#L53

https://github.com/cloudfoundry/dep-cnb/blob/c5873ee8857227353198c0080b5fd07ca4f2f0bf/cmd/detect/main.go#L64

Can you provide a sample app?
Any go dep application

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by Zanadar** [comment]
Closing with https://github.com/cloudfoundry/dep-cnb/pull/4
