### ISSUE TITLE
The buildpack reuses layers incorrectly even when there are changes to the go source code

### ISSUE THREAD

**Issue by djoyahoy** [cloudfoundry/dep-cnb#7]
What version of the buildpack you are using?
0.0.7

If you were attempting to accomplish a task, what was it you were attempting to do?
Build a go app that has fresh changes

What did you expect to happen?
The app-layer is not reused, instead a new layer is exported.

What was the actual behavior?
The app-layer is reused.

Can you provide a sample app?
This should fail with any go app as long as you do not update the Gopkg.lock

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

@ndon55555

**Comment by ndon55555** [comment]
Should be addressed in [this](https://github.com/cloudfoundry/dep-cnb/commit/77c6393a5fb9039589cf429dd902362edda3939e) commit
